### ISSUE TITLE
训练过程始终使用同一个问题初始化环境吗

### ISSUE THREAD

**Issue by zhang-xinyuan** [weixians/JobSchedule#1]
你好，请问训练时每次reset环境，都是初始化为同一个问题吗？网络训练好之后将新的问题作为输入效果怎么样

**Comment by weixians** [comment]
您好，可以看一下run_ddqn_category.py这个文件，这里用的是所有同样大小的数据来训练的

**Comment by weixians** [comment]
> 你好，请问训练时每次reset环境，都是初始化为同一个问题吗？网络训练好之后将新的问题作为输入效果怎么样

您好，可以看一下run_ddqn_category.py这个文件，这里用的是所有同样大小的数据来训练的

**Comment by zhang-xinyuan** [comment]
好的，非常感谢！
